spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/databasename
    username: username
    password: password
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl_auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
